language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jmarsan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jmarsan/docker-react npm run test
    